spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test-db.cvmid5810146.ap-northeast-2.rds.amazonaws.com:3306/camping?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: 1234567890
  jpa:
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret: CAMPINGSHOP


cloud:
  aws:
    s3:
      bucket: suoh-camping
    credentials:
      access-key: AKIA4ZZFZ2IU3ETJVA7D
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
